version: '3.8'

services:
  web_app:
    image: athuls121/web_app
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    ports:
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      - redis


  redis:
    image: redis:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: overlay
